import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import importPlugin from "eslint-plugin-import";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      // Auto-generated by Next.js; never hand-edited, so don't lint it
      // (it uses triple-slash references the codebase otherwise bans).
      "**/next-env.d.ts",
      "**/.turbo/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/generated/**",
      // Config files live outside tsconfig's include and aren't worth typechecking.
      "**/eslint.config.{js,mjs,cjs}",
      "**/vitest.config.{ts,js,mjs}",
      "**/playwright.config.{ts,js}",
      "**/next.config.{ts,js,mjs}",
      "**/postcss.config.{ts,js,mjs}",
      "**/tailwind.config.{ts,js,mjs}",
      "**/*.config.{ts,js,mjs}",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    plugins: { import: importPlugin },
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["*.config.*", "eslint.config.*"],
        },
        tsconfigRootDir: process.cwd(),
      },
    },
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: false }],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "import/order": [
        "warn",
        {
          groups: ["builtin", "external", "internal", ["parent", "sibling", "index"], "type"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],

      // ---- pragmatic strictness downgrades ----
      // ``strictTypeChecked`` is a useful audit baseline, but a few
      // rules surface mostly stylistic noise on a fast-moving app
      // codebase. Keep the signal as ``warn`` so the audit trail
      // stays in editors / PR comments, but stop CI from going red
      // on a missing `{}` around an inline arrow function. Drag them
      // back to "error" when the project enters maintenance mode.
      "@typescript-eslint/no-non-null-assertion": "warn",
      "@typescript-eslint/no-confusing-void-expression": "warn",
      "@typescript-eslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/dot-notation": "warn",
      "@typescript-eslint/consistent-type-definitions": "warn",
      "@typescript-eslint/no-invalid-void-type": "warn",
      "@typescript-eslint/prefer-nullish-coalescing": "warn",
      "@typescript-eslint/restrict-template-expressions": "warn",
      "@typescript-eslint/prefer-optional-chain": "warn",
      "@typescript-eslint/no-dynamic-delete": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/require-await": "warn",
      // ``ElementRef`` is deprecated by React 19 types but shadcn/ui
      // hasn't bumped yet. Downgrade so editor still flags it but CI
      // doesn't fail until upstream catches up.
      "@typescript-eslint/no-deprecated": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/restrict-plus-operands": "warn",
      "@typescript-eslint/no-unnecessary-type-parameters": "warn",
      "@typescript-eslint/no-unnecessary-type-conversion": "warn",
    },
  },
  prettier,
);
