-- scripts/seed/genshin_post_review.sql
--
-- GENERATED by scripts/seed/build_genshin_post.py — do not edit by hand.
--
-- Review fixes to the imported Russian Genshin draft, plus en/uz translations.
-- The importer lands Russian only and leaves the brand unset; both are dealt
-- with here.
--
-- The Russian body is patched with exact string swaps rather than replaced, so
-- the diff is the five defects the review found and nothing else. Each swap
-- asserts it changed something: a silent no-op would mean the draft moved under
-- us and the fix never landed.
--
-- The two new bodies went through the API's own markdown_to_html +
-- sanitize_body, so no tag in them can be one the fail-closed allowlist drops.
--
-- Stays a DRAFT. Publishing is the owner's call in the admin.

BEGIN;

-- 1. The brand. `ck_blog_posts_brand_unless_draft` lets a draft carry none,
-- which is why the importer's row was legal — and why publishing would have
-- failed on it. It is a Genshin guide; the brand is genshin-impact.
UPDATE blog_posts SET primary_brand_id = (SELECT id FROM brands WHERE slug = 'genshin-impact')
WHERE id = '01a0a91f-f25d-7d60-81be-4e5926294912';

-- 2. Review fixes to the Russian body.
-- Not a Genshin word. The collectibles that level the Statues of the Seven — which the same sentence already mentions — are окулы (anemoculus, geoculus and so on).
DO $do$
BEGIN
    IF EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$оракумы$x$ in body_html) > 0
    ) THEN
        UPDATE blog_post_translations
        SET body_html = replace(body_html, $x$оракумы$x$, $x$окулы$x$)
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru';
    ELSIF NOT EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$окулы$x$ in body_html) > 0
    ) THEN
        RAISE EXCEPTION
            'neither the original nor the fix is present — the draft changed: %',
            $x$оракумы$x$;
    END IF;
END
$do$;

-- «Примитивные материалы» is nothing in the game; the advice is to hoard ascension materials, and every other term in the guide is the correct Russian one.
DO $do$
BEGIN
    IF EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$копите примитивные материалы$x$ in body_html) > 0
    ) THEN
        UPDATE blog_post_translations
        SET body_html = replace(body_html, $x$копите примитивные материалы$x$, $x$копите материалы возвышения$x$)
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru';
    ELSIF NOT EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$копите материалы возвышения$x$ in body_html) > 0
    ) THEN
        RAISE EXCEPTION
            'neither the original nor the fix is present — the draft changed: %',
            $x$копите примитивные материалы$x$;
    END IF;
END
$do$;

-- The search phrase pasted mid-sentence in lowercase, twice. It reads as stuffing to a person and buys nothing from a search engine that has the title, the heading and the URL already.
DO $do$
BEGIN
    IF EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$Этот genshin impact гайд для новичков объясняет$x$ in body_html) > 0
    ) THEN
        UPDATE blog_post_translations
        SET body_html = replace(body_html, $x$Этот genshin impact гайд для новичков объясняет$x$, $x$Этот гайд объясняет$x$)
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru';
    ELSIF NOT EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$Этот гайд объясняет$x$ in body_html) > 0
    ) THEN
        RAISE EXCEPTION
            'neither the original nor the fix is present — the draft changed: %',
            $x$Этот genshin impact гайд для новичков объясняет$x$;
    END IF;
END
$do$;

-- Second instance of the same phrase.
DO $do$
BEGIN
    IF EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$Любой genshin impact гайд для новичков начинается с одного$x$ in body_html) > 0
    ) THEN
        UPDATE blog_post_translations
        SET body_html = replace(body_html, $x$Любой genshin impact гайд для новичков начинается с одного$x$, $x$Любой гайд для новичков начинается с одного$x$)
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru';
    ELSIF NOT EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$Любой гайд для новичков начинается с одного$x$ in body_html) > 0
    ) THEN
        RAISE EXCEPTION
            'neither the original nor the fix is present — the draft changed: %',
            $x$Любой genshin impact гайд для новичков начинается с одного$x$;
    END IF;
END
$do$;

-- The one link that had to be here was missing: a Genshin guide pointed at the homepage instead of the Genshin top-up page. The article had no link into /store at all.
DO $do$
BEGIN
    IF EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$<a href="https://yupay.uz">Yupay</a> продаёт пополнения для игр в узбекских сумах с локальными способами оплаты$x$ in body_html) > 0
    ) THEN
        UPDATE blog_post_translations
        SET body_html = replace(body_html, $x$<a href="https://yupay.uz">Yupay</a> продаёт пополнения для игр в узбекских сумах с локальными способами оплаты$x$, $x$<a href="https://yupay.uz/store/genshin-impact">Yupay</a> пополняет Genshin Impact по UID в узбекских сумах, картами Uzcard и Humo$x$)
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru';
    ELSIF NOT EXISTS (
        SELECT 1 FROM blog_post_translations
        WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale = 'ru'
          AND position($x$<a href="https://yupay.uz/store/genshin-impact">Yupay</a> пополняет Genshin Impact по UID в узбекских сумах, картами Uzcard и Humo$x$ in body_html) > 0
    ) THEN
        RAISE EXCEPTION
            'neither the original nor the fix is present — the draft changed: %',
            $x$<a href="https://yupay.uz">Yupay</a> продаёт пополнения для $x$;
    END IF;
END
$do$;

-- 3. The translations. Delete-then-insert so a re-run replaces them.
DELETE FROM blog_post_translations WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale IN ('en','uz');
INSERT INTO blog_post_translations (post_id, locale, slug, title, excerpt, body_html, seo_title, seo_description)
VALUES
    ('01a0a91f-f25d-7d60-81be-4e5926294912', 'en', $x$genshin-impact$x$, $x$How to play Genshin Impact: a beginner's guide$x$, $x$Elements and reactions matter more than character levels, the 5-star pity lands at 90 wishes, and Primogems come free if you know where to look. Everything a new Traveler needs.$x$,
     $x$<h2>The short version</h2>
<ul>
<li>Genshin Impact draws around 15 million monthly players as of September 2025, so a newcomer is never short of a community or advice.</li>
<li>The seven elements and the reactions between them matter more than a character's level: the right pairing out-damages brute-force levelling.</li>
<li>The hard pity for a 5-star character lands on the 90th wish and soft pity starts around the 74th, so it pays to save deliberately.</li>
<li>Daily commissions, world exploration and the Spiral Abyss give a steady flow of Primogems for free.</li>
</ul>
<p>Starting Genshin Impact is simple: download it, finish the tutorial in Mondstadt, and concentrate on learning the elements rather than levelling blindly. This guide covers how the game works, how characters and the banner and wish systems fit together, and how to earn Primogems without spending much.</p>
<p>It remains one of the most popular open-world RPGs there is. As of September 2025 it had roughly 15 million players a month (<a href="https://www.dexerto.com/genshin-impact/how-many-people-play-genshin-impact-player-count-tracker-1683360/">Dexerto</a>, 2025), which means there is a large community around you and whatever problem you hit, somebody has already solved it.</p>
<h2>Where to begin: your first steps in Teyvat</h2>
<p>Every beginner's guide starts the same way: play the prologue and choose the Traveler's gender. That opens up the city of Mondstadt, the Anemo element and your first quests. Do not rush to close everything at once — explore the map calmly and gather resources.</p>
<p>Adventure Rank unlocks new systems gradually. It rises with quests, waypoints and domains. While your rank is low, hoard ascension materials and do not spend levelling resources on weak characters.</p>
<p>Three habits that save you days later:</p>
<ul>
<li>Unlock every waypoint and Statue of the Seven you come across.</li>
<li>Pick the local flora — you will need it to ascend your heroes.</li>
<li>Do the four daily commissions for the experience and the Primogems.</li>
</ul>
<p>The Spiral Abyss and world bosses can wait until your team is stronger. Understanding the basics of combat comes first.</p>
<h2>How characters and elements work</h2>
<p>The combat system rests on seven elements: Pyro, Hydro, Electro, Cryo, Anemo, Geo and Dendro. Each character belongs to one of them. A team's strength comes not from its levels but from how well those elements combine.</p>
<p>When two elements meet on one enemy, an elemental reaction fires. Hydro and Pyro give Vaporize and amplified damage. Electro and Hydro cause Electro-Charged. Cryo and Pyro give Melt. Reactions are what turn a team that looks weak on paper into a strong one.</p>
<p>How do you use that? Build a party of four so the elements complement each other. One deals the main damage, the second applies a second element for the reaction, the third heals or shields, the fourth buffs.</p>
<p>Team roles usually break down like this:</p>
<ul>
<li>The main DPS holds the field and attacks most.</li>
<li>The sub-DPS applies the second element for reactions.</li>
<li>A healer or shielder keeps the team alive.</li>
<li>A buffer raises the whole group's damage.</li>
</ul>
<p>Understanding reactions matters more than owning rare characters. A well-built team of starter heroes clears almost the entire story.</p>
<h2>The banner and wish system, explained</h2>
<p>New characters and weapons come from wishes, the game's gacha system. Wishes are paid for with special items: Intertwined Fates for the character and weapon banners. The maths here is worth knowing, so you do not spend Primogems blindly.</p>
<p>The base rate for a 5-star hero is low, around 0.6%. But the game protects you with two mechanics. Soft pity begins around the 74th wish, where the rate climbs sharply. Hard pity triggers on the 90th wish of a character banner: a 5-star is guaranteed.</p>
<p>Then the 50/50 system applies. Your first guaranteed 5-star has a 50% chance of being the featured character. If you lose it and get a random one from the standard pool, the next 5-star is guaranteed to be the featured one. Worst case, the character you want costs about 180 wishes.</p>
<p>The practical takeaway for a beginner is simple. Do not spread single wishes across banners. Save for a specific character who will strengthen your team, and walk the counter to pity deliberately.</p>
<h2>Levelling up without spending</h2>
<p>Genshin Impact is entirely free, and you can finish it without paying a thing. The main rule of economy: invest only in the heroes you actually play. Spreading experience and materials across everyone slows your progress more than anything else.</p>
<p>Level one main DPS to the cap of your Adventure Rank first. Ascend them on time to lift the level ceiling. Level talents on whoever deals the damage, not on the support.</p>
<p>Artifacts often matter more than a character's level. Do not chase perfect stats early on. Put on any set with useful bonuses and replace it as you go. Leave farming the best artifacts for the late game.</p>
<p>A few rules that protect your resources:</p>
<ul>
<li>Do not spend Original Resin on domains while your team is weak.</li>
<li>Eat attack and defence food before hard fights.</li>
<li>Cooking and alchemy cover a lot of needs for free.</li>
</ul>
<p>That approach gives steady progress with no money spent. There is no hurry: the game holds hundreds of hours of content.</p>
<h2>How to earn Primogems quickly</h2>
<p>Primogems are the main wish currency, and a beginner can earn them steadily and for free. The key is not to miss the regular sources and to explore actively. Played systematically, it adds up to a decent sum every month.</p>
<p>The main free sources:</p>
<ul>
<li>Daily commissions: four tasks a day for quick Primogems.</li>
<li>Exploration: chests, puzzles and oculi are scattered across the map.</li>
<li>Spiral Abyss: a combat challenge with a large reward each cycle.</li>
<li>Events: seasonal events often hand out hundreds of Primogems over a couple of evenings.</li>
<li>Achievements and mail gifts from the developers.</li>
</ul>
<p>One more tip: open new regions. Every new territory means dozens of chests and new Statues of the Seven, which also give Primogems. Exploration stays the most underrated source of currency among beginners.</p>
<p>If you do decide to top up, use a convenient local service. <a href="https://yupay.uz/en/store/genshin-impact">Yupay</a> tops up Genshin Impact by UID in Uzbek sum, with Uzcard and Humo cards — easier than working out foreign cards. If you play on Steam too, our guide on <a href="https://yupay.uz/en/blog/steam">topping up Steam in Uzbekistan</a> will help.</p>
<p>Start small: today, do the four daily commissions and open one new stretch of map. After a couple of weeks of that routine you will have saved for your first deliberate run of wishes, and you will see how the system rewards patient players.</p>$x$,
     $x$How to play Genshin Impact: a beginner's guide$x$, $x$A beginner's guide to Genshin Impact: first steps in Teyvat, how elemental reactions work, the wish and pity system explained, and how to earn Primogems without spending.$x$),
    ('01a0a91f-f25d-7d60-81be-4e5926294912', 'uz', $x$genshin-impact$x$, $x$Genshin Impactda qanday oʻynash kerak: yangi boshlovchilar uchun qoʻllanma$x$, $x$Elementlar va ular orasidagi reaksiyalar qahramon darajasidan muhimroq, 5 yulduzli kafolat 90-duoda keladi, Boshlangʻich kristallarni esa bepul yigʻish mumkin.$x$,
     $x$<h2>Eng muhimi</h2>
<ul>
<li>2025-yil sentabr holatiga koʻra Genshin Impactni oyiga 15 millionga yaqin odam oʻynaydi, shuning uchun yangi oʻyinchi hamjamiyat va maslahatni oson topadi.</li>
<li>Yetti element va ular orasidagi reaksiyalar qahramon darajasidan muhimroq: toʻgʻri tanlangan juftlik koʻr-koʻrona darajani oshirishdan koʻra koʻproq zarar beradi.</li>
<li>5 yulduzli qahramon uchun qattiq kafolat 90-duoda ishlaydi, yumshoq kafolat esa taxminan 74-duodan boshlanadi — demak kristallarni ongli ravishda yigʻish kerak.</li>
<li>Kundalik topshiriqlar, dunyoni oʻrganish va Burama Tubsizlik bepul kristallarning barqaror manbasi.</li>
</ul>
<p>Genshin Impactni boshlash oson: oʻyinni yuklab oling, Mondshtadtdagi darsni yakunlang va koʻr-koʻrona daraja oshirish emas, elementlarni oʻrganishga eʼtibor bering. Bu qoʻllanma oʻyin qanday ishlashini, qahramonlar, banner va duo tizimi qanday bogʻlanishini hamda katta xarajatsiz Boshlangʻich kristallarni qanday olishni tushuntiradi.</p>
<p>Oʻyin ochiq dunyoli eng mashhur rol oʻyinlaridan biri boʻlib qolmoqda. 2025-yil sentabr holatiga koʻra unda oyiga 15 millionga yaqin odam oʻynaydi (<a href="https://www.dexerto.com/genshin-impact/how-many-people-play-genshin-impact-player-count-tracker-1683360/">Dexerto</a>, 2025). Bu atrofingizda katta hamjamiyat borligini va duch kelgan muammoyingizni kimdir allaqachon hal qilganini anglatadi.</p>
<h2>Nimadan boshlash kerak: Teyvatdagi ilk qadamlar</h2>
<p>Har qanday qoʻllanma bir xil boshlanadi: prologni oʻtang va Sayyohning jinsini tanlang. Shundan soʻng Mondshtadt shahri, Anemo elementi va ilk kvestlar ochiladi. Hammasini birdan yopishga shoshilmang — xaritani xotirjam oʻrganing va resurs yigʻing.</p>
<p>Sarguzasht darajasi yangi mexanikalarni bosqichma-bosqich ochadi. U kvestlar, teleportlar va zindonlar hisobiga oʻsadi. Daraja past ekan, yuksaltirish materiallarini yigʻing va kuchsiz qahramonlarga resurs sarflamang.</p>
<p>Keyinchalik kunlab vaqtni tejaydigan uchta odat:</p>
<ul>
<li>Koʻrgan har bir teleport va Yettilik haykalini oching.</li>
<li>Mahalliy oʻsimliklarni yigʻing — ular qahramonlarni yuksaltirish uchun kerak.</li>
<li>Har kuni toʻrtta topshiriqni tajriba va kristallar uchun bajaring.</li>
</ul>
<p>Burama Tubsizlik va dunyo bosslari jamoangiz kuchayguncha kutib turadi. Avval jang qoidalarini tushunish muhimroq.</p>
<h2>Qahramonlar va elementlar qanday ishlaydi</h2>
<p>Jang tizimi asosida yettita element yotadi: Piro, Gidro, Elektro, Krio, Anemo, Geo va Dendro. Har bir qahramon bitta elementga tegishli. Jamoaning kuchi darajaga emas, balki bu elementlarni qanchalik oqilona birlashtirishingizga bogʻliq.</p>
<p>Bitta raqibda ikkita element uchrashganda element reaksiyasi ishga tushadi. Gidro va Piro Bugʻlanishni va kuchaytirilgan zararni beradi. Elektro va Gidro Zaryadlanishni chaqiradi. Krio va Piro Erishni beradi. Aynan reaksiyalar qogʻozda kuchsiz koʻringan jamoani kuchliga aylantiradi.</p>
<p>Buni amalda qanday qoʻllash kerak? Toʻrt qahramondan iborat jamoani elementlar bir-birini toʻldiradigan qilib yigʻing. Biri asosiy zarar beradi, ikkinchisi reaksiya uchun element qoʻyadi, uchinchisi davolaydi yoki himoya qiladi, toʻrtinchisi kuchaytiradi.</p>
<p>Jamoadagi rollar odatda shunday taqsimlanadi:</p>
<ul>
<li>Asosiy zarar beruvchi maydonda turadi va eng koʻp uradi.</li>
<li>Yordamchi zarar beruvchi reaksiya uchun ikkinchi elementni qoʻyadi.</li>
<li>Davolovchi yoki qalqon beruvchi jamoani tirik saqlaydi.</li>
<li>Kuchaytiruvchi butun guruh zararini oshiradi.</li>
</ul>
<p>Reaksiyalarni tushunish noyob qahramonlarga ega boʻlishdan muhimroq. Boshlangʻich qahramonlardan yaxshi yigʻilgan toʻrtlik deyarli butun syujetni oʻtadi.</p>
<h2>Banner va duo tizimining tahlili</h2>
<p>Yangi qahramon va qurollar duolar orqali olinadi — bu oʻyindagi gacha tizimi. Duolar uchun maxsus buyumlar kerak: qahramon va qurol bannerlari uchun Chirmashgan taqdirlar. Kristallarni koʻr-koʻrona sarflamaslik uchun bu yerdagi matematikani bilish foydali.</p>
<p>5 yulduzli qahramon tushishining bazaviy ehtimoli past — taxminan 0,6%. Lekin oʻyin sizni ikkita mexanika bilan himoya qiladi. Yumshoq kafolat taxminan 74-duodan boshlanadi, oʻshanda ehtimol keskin oshadi. Qattiq kafolat qahramon bannerining 90-duosida ishlaydi: 5 yulduzli albatta tushadi.</p>
<p>Keyin 50/50 tizimi ishga tushadi. Kafolat bilan olingan birinchi 5 yulduzli qahramoningiz 50% ehtimol bilan aynan bannerdagi qahramon boʻladi. Omad kelmay, umumiy toʻplamdan tasodifiy qahramon tushsa, keyingi 5 yulduzli aniq bannerdagisi boʻladi. Eng yomon holatda kerakli qahramon taxminan 180 duoga tushadi.</p>
<p>Yangi boshlovchi uchun amaliy xulosa oddiy. Turli bannerlarda bittadan duo aylantirmang. Jamoangizni kuchaytiradigan aniq bir qahramonga yigʻing va hisoblagichni ongli ravishda kafolatgacha olib boring.</p>
<h2>Katta xarajatsiz daraja oshirish maslahatlari</h2>
<p>Genshin Impact toʻliq bepul va uni bironta ham donatsiz oʻtish mumkin. Tejashning asosiy qoidasi: resurslarni faqat oʻzingiz haqiqatan oʻynaydigan qahramonlarga sarflang. Tajriba va materiallarni hammaga sochish taraqqiyotni eng koʻp sekinlashtiradi.</p>
<p>Avval bitta asosiy zarar beruvchini Sarguzasht darajangiz chegarasigacha koʻtaring. Daraja cheklovini olib tashlash uchun uni oʻz vaqtida yuksaltiring. Isteʼdodlarni yordamchida emas, asosiy zarar beruvchida oshiring.</p>
<p>Artefaktlar koʻpincha qahramon darajasidan muhimroq. Boshida mukammal xususiyatlar ortidan quvmang. Mos bonusli istalgan toʻplamni kiying va oʻtish davomida almashtiring. Eng yaxshi artefaktlarni yigʻishni keyingi bosqichga qoldiring.</p>
<p>Resurslarni asraydigan bir nechta qoida:</p>
<ul>
<li>Jamoa kuchsiz ekan, zindonlarga Boshlangʻich smolani sarflamang.</li>
<li>Ogʻir janglardan oldin hujum va himoyani oshiradigan taomlarni yeng.</li>
<li>Pazandalik va alkimyo koʻp ehtiyojni bepul qoplaydi.</li>
</ul>
<p>Bunday yondashuv pul sarflamasdan bir tekis taraqqiyot beradi. Shoshilishga hojat yoʻq: oʻyinda yuzlab soatlik kontent bor.</p>
<h2>Kristallarni qanday tez olish mumkin</h2>
<p>Boshlangʻich kristallar — duolar uchun asosiy valyuta va yangi oʻyinchi ularni barqaror hamda bepul olishi mumkin. Kalit shundaki, muntazam manbalarni oʻtkazib yubormaslik va dunyoni faol oʻrganish kerak. Tizimli oʻynaganda har oyda anchagina summa toʻplanadi.</p>
<p>Kristallarning asosiy bepul manbalari:</p>
<ul>
<li>Kundalik topshiriqlar: kuniga toʻrtta vazifa tez kristal beradi.</li>
<li>Dunyoni oʻrganish: sandiqlar, boshqotirmalar va okullar butun xarita boʻylab sochilgan.</li>
<li>Burama Tubsizlik: har siklda katta mukofotli jangovar sinov.</li>
<li>Tadbirlar: mavsumiy tadbirlar koʻpincha bir necha kechada yuzlab kristal beradi.</li>
<li>Yutuqlar va ishlab chiquvchilardan pochta sovgʻalari.</li>
</ul>
<p>Alohida maslahat: yangi hududlarni oching. Har bir yangi hudud — oʻnlab sandiq va yangi Yettilik haykallari, ular ham kristal beradi. Dunyoni oʻrganish yangi oʻyinchilar orasida eng kam baholanadigan valyuta manbasi boʻlib qolmoqda.</p>
<p>Agar baribir hisobni toʻldirishga qaror qilsangiz, qulay mahalliy xizmatdan foydalaning. Masalan, <a href="https://yupay.uz/uz/store/genshin-impact">Yupay</a> Genshin Impactni UID boʻyicha oʻzbek soʻmida, Uzcard va Humo kartalari bilan toʻldiradi — chet el kartalari bilan boshni qotirishdan qulayroq. Steamda ham oʻynaydiganlarga <a href="https://yupay.uz/uz/blog/steam">Oʻzbekistonda Steamni qanday toʻldirish</a> boʻyicha qoʻllanmamiz asqotadi.</p>
<p>Kichikdan boshlang: bugun toʻrtta kundalik topshiriqni bajaring va xaritaning bitta yangi qismini oching. Bir necha haftalik shunday tartibdan soʻng birinchi ongli duolar seriyasiga yigʻasiz va tizim sabrli oʻyinchilarni qanday mukofotlashini koʻrasiz.</p>$x$,
     $x$Genshin Impactda qanday oʻynash kerak: yangi boshlovchilar uchun qoʻllanma$x$, $x$Genshin Impact boʻyicha yangi boshlovchilar uchun qoʻllanma: Teyvatdagi ilk qadamlar, element reaksiyalari, duo va kafolat tizimi hamda kristallarni bepul yigʻish yoʻllari.$x$);

-- 4. The same four questions, in the same order as the Russian rows.
DELETE FROM blog_post_faqs WHERE post_id = '01a0a91f-f25d-7d60-81be-4e5926294912' AND locale IN ('en','uz');
INSERT INTO blog_post_faqs (id, post_id, locale, sort_order, question, answer)
VALUES
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'en', 0, $x$How many wishes guarantee a 5-star character?$x$,
     $x$Hard pity triggers on the 90th wish of a character banner — a 5-star is guaranteed there. Soft pity starts around the 74th, where the rate climbs sharply, so most 5-stars arrive before 90. With a lost 50/50 the featured character costs about 180 wishes at worst.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'uz', 0, $x$Kafolatlangan 5 yulduzli qahramon uchun nechta duo kerak?$x$,
     $x$Qattiq kafolat qahramon bannerining 90-duosida ishlaydi — u yerda 5 yulduzli albatta tushadi. Yumshoq kafolat taxminan 74-duodan boshlanadi va ehtimol keskin oshadi, shuning uchun koʻpchilik 5 yulduzlilar 90 gacha keladi. 50/50 yutqazilganda kerakli qahramon eng yomon holatda taxminan 180 duoga tushadi.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'en', 1, $x$Is Genshin Impact free?$x$,
     $x$Yes, completely. The story, the open world and the events are all available without paying, and you can finish the game without spending. Wishes for new characters are what money buys, and Primogems for those can be earned in-game.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'uz', 1, $x$Genshin Impact bepulmi?$x$,
     $x$Ha, toʻliq bepul. Syujet, ochiq dunyo va tadbirlar toʻlovsiz ochiq, oʻyinni pul sarflamasdan oxirigacha oʻtish mumkin. Pulga yangi qahramonlar uchun duolar olinadi, ular uchun kerakli kristallarni esa oʻyin ichida yigʻsa boʻladi.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'en', 2, $x$How does a beginner save Primogems quickly?$x$,
     $x$Do the four daily commissions every day, explore new regions for chests and oculi, and clear the Spiral Abyss each cycle. Seasonal events add hundreds over a couple of evenings. Played steadily, that is a meaningful sum every month with nothing spent.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'uz', 2, $x$Yangi oʻyinchi kristallarni qanday tez yigʻadi?$x$,
     $x$Har kuni toʻrtta kundalik topshiriqni bajaring, sandiq va okullar uchun yangi hududlarni oching, har siklda Burama Tubsizlikni yeching. Mavsumiy tadbirlar bir necha kechada yuzlab kristal qoʻshadi. Muntazam oʻynaganda bu hech narsa sarflamasdan har oyda sezilarli summa.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'en', 3, $x$What is the 50/50 system in wishes?$x$,
     $x$Your first guaranteed 5-star has a 50% chance of being the banner's featured character. Lose that coin flip and you get a random 5-star from the standard pool — but then the next one is guaranteed to be the featured character.$x$),
    (gen_random_uuid(), '01a0a91f-f25d-7d60-81be-4e5926294912', 'uz', 3, $x$Duolardagi 50/50 tizimi nima?$x$,
     $x$Kafolat bilan olingan birinchi 5 yulduzlingiz 50% ehtimol bilan bannerdagi qahramon boʻladi. Bu tanga tashlashda yutqazsangiz, umumiy toʻplamdan tasodifiy 5 yulduzli tushadi — lekin keyingisi aniq bannerdagi qahramon boʻlishi kafolatlanadi.$x$);

COMMIT;
