-- scripts/seed/steam_gifts_blog_post.sql
--
-- GENERATED by scripts/seed/build_steam_gifts_post.py — do not edit by hand.
-- Edit the markdown in that script and re-run it.
--
-- One guide post for the `steam-gifts` brand, in ru/en/uz, with 4 FAQ entries per
-- locale. The bodies were rendered through the API's own `markdown_to_html` +
-- `sanitize_body`, so what lands here is byte-for-byte what an editor pasting the
-- same markdown into the admin would have stored — no tag in it can be one the
-- fail-closed allowlist drops on read.
--
-- Inserted as a DRAFT on purpose. It is editorial copy on a public site: the owner
-- reads it and presses publish in the admin. `ck_blog_posts_brand_unless_draft`
-- allows a draft with no brand, but this one names its brand anyway so publishing
-- is the only step left.
--
-- Idempotent: keyed on the ru slug, rebuilt via delete-then-insert, one
-- transaction. Re-running replaces the post and drops any likes/views it had
-- collected (ON DELETE CASCADE) — harmless on a draft, worth knowing once it is
-- published.

BEGIN;

DELETE FROM blog_posts WHERE id IN (
    SELECT post_id FROM blog_post_translations
    WHERE locale = 'ru' AND slug = $x$kak-kupit-igru-v-steam-iz-uzbekistana$x$
);

WITH new_post AS (
    INSERT INTO blog_posts (id, kind, status, primary_brand_id, show_buy_card, pin_on_brand)
    SELECT gen_random_uuid(), 'guide', 'draft', b.id, true, false
    FROM brands b WHERE b.slug = 'steam-gifts'
    RETURNING id
),
tr AS (
    INSERT INTO blog_post_translations (post_id, locale, slug, title, excerpt, body_html, seo_title, seo_description)
    SELECT np.id, v.locale, v.slug, v.title, v.excerpt, v.body_html, v.seo_title, v.seo_description
    FROM new_post np, (VALUES
        ('ru', $x$kak-kupit-igru-v-steam-iz-uzbekistana$x$, $x$Как купить игру в Steam из Узбекистана$x$, $x$Узбекистанская карта в Steam не проходит, а цены для нашего региона редко самые низкие. Разбираем, как купить игру легально, за сумы и обычно дешевле, чем в самом Steam.$x$,
         $x$<p>Купить игру в Steam из Узбекистана — задача, у которой два разных препятствия, и
их обычно путают. Первое: узбекистанская карта в Steam чаще всего не проходит.
Второе, менее очевидное: даже когда оплата проходит, цена для нашего региона
редко оказывается самой низкой из возможных. Ниже — что с этим делать.</p>
<h2>Почему карта не проходит</h2>
<p>Steam принимает оплату не отовсюду и не любыми картами. Uzcard и Humo — это
локальные платёжные системы, за пределами страны они не работают, а
международные карты есть далеко не у всех. Отсюда все обходные пути, которыми
полон интернет: чужие аккаунты, VPN, «пополню за процент». Часть из них просто
неудобна, часть откровенно опасна — про это в конце.</p>
<h2>Цена в Steam зависит от региона</h2>
<p>Это ключевая вещь, про которую мало кто знает. У Steam нет одной цены на игру.
Издатель назначает разные цены для разных регионов, и разрыв бывает
двукратным. Цена для Узбекистана — не самая высокая в мире, но и не самая
низкая: соседние регионы часто дешевле.</p>
<p>Вот три реальных примера, снятых с витрины Steam в сентябре 2026 года:</p>
<table>
<thead>
<tr>
<th>Игра</th>
<th>Steam для Узбекистана</th>
<th>Наша цена</th>
</tr>
</thead>
<tbody>
<tr>
<td>West Escape</td>
<td>$0.99</td>
<td>$0.78</td>
</tr>
<tr>
<td>Age of Empires IV</td>
<td>$27.99</td>
<td>$21.20</td>
</tr>
<tr>
<td>Black Myth: Wukong</td>
<td>$59.99</td>
<td>$41.45</td>
</tr>
</tbody>
</table>
<p>Скажем сразу и честно: так бывает не всегда. Мы проверили 21 случайную игру из
каталога — дешевле оказались 17, примерно вровень 2, и на двух играх мы были
дороже. Медианная экономия среди выигрышных — около 15%, максимальная доходила
до 54%. Поэтому правильная формулировка — «обычно дешевле», а не «всегда»; цену
видно до оплаты, так что сравнить можно самому за десять секунд.</p>
<h2>Подарок Steam, а не ключ</h2>
<p>Способ, которым это работает легально, называется подарком Steam. Игра
покупается в том регионе, где она доступна, и отправляется на аккаунт
получателя штатным механизмом самого Steam — тем же, которым вы дарите игру
другу на день рождения.</p>
<p>Что из этого следует:</p>
<ul>
<li>Никаких ключей вводить не нужно. Игра появляется в библиотеке сама.</li>
<li>Пароль от аккаунта не нужен никому. Достаточно публичной ссылки на профиль.</li>
<li>Игра остаётся у получателя навсегда, как любая купленная.</li>
<li>Аккаунт остаётся ваш. Никакого «общего» или «арендованного» аккаунта.</li>
</ul>
<h2>Как купить: по шагам</h2>
<ol>
<li>Найдите игру в каталоге — поиском по названию.</li>
<li>Выберите издание, если их несколько, и регион аккаунта получателя.</li>
<li>Вставьте ссылку на профиль Steam. Ник и аватар покажутся сразу — это
страховка от опечатки в ссылке.</li>
<li>Оплатите картой Uzcard или Humo через Click, Payme или Uzum.</li>
<li>Дождитесь подарка. Обычно он приходит в течение часа.</li>
</ol>
<h2>Главная ошибка — регион аккаунта</h2>
<p>Подарок можно принять только в том регионе, для которого он куплен. Если
аккаунт получателя числится за другой страной, Steam просто не даст нажать
«Принять» — и это самая частая причина, по которой заказ застревает.</p>
<p>Проверяется за полминуты: Steam → «Об аккаунте» → строка «Страна». Это тот
самый регион, который нужно выбрать при оформлении. Если не совпадает — лучше
выяснить до оплаты, а не после.</p>
<h2>Если игра оказалась дополнением</h2>
<p>DLC работает только поверх основной игры. Подарить дополнение человеку, у
которого основной игры нет, технически можно — пользы от этого не будет
никакой, пока он не купит базовую версию. В карточке такие позиции помечены,
но на всякий случай стоит посмотреть.</p>
<h2>Про безопасность, коротко</h2>
<p>Единственное, что нужно для подарка, — ссылка на профиль. Она публичная, её
видно любому.</p>
<p>Никто и никогда не должен просить у вас пароль от Steam, код из
Steam Guard или доступ к почте ради покупки игры. Если просят — это не
магазин, а кража аккаунта, и никакая цена этого не стоит. Правило простое и
не знает исключений.</p>$x$,
         $x$Как купить игру в Steam из Узбекистана за сумы — YuPay$x$, $x$Пошаговая инструкция: как купить игру в Steam из Узбекистана, оплатить сумами картой Uzcard или Humo и не ошибиться с регионом аккаунта. С реальным сравнением цен.$x$),
        ('en', $x$how-to-buy-steam-games-from-uzbekistan$x$, $x$How to buy Steam games from Uzbekistan$x$, $x$An Uzbek card usually will not go through on Steam, and the Uzbekistan price is rarely the lowest one. Here is how to buy a game legally, in sum, and usually cheaper.$x$,
         $x$<p>Buying a Steam game from Uzbekistan runs into two separate obstacles, and they
are usually confused with each other. First: an Uzbek card will most often not
go through on Steam. Second, and less obvious: even when payment does go
through, the price set for our region is rarely the lowest one available. Here
is what to do about both.</p>
<h2>Why the card is declined</h2>
<p>Steam does not accept payment from everywhere or from every card. Uzcard and
Humo are domestic payment systems and do not work abroad, and international
cards are far from universal here. That is where the workarounds the internet
is full of come from: borrowed accounts, VPNs, &quot;I'll top you up for a cut&quot;.
Some of those are merely inconvenient. Some are outright dangerous — more on
that at the end.</p>
<h2>A Steam price depends on the region</h2>
<p>This is the part few people know. Steam does not have one price per game. The
publisher sets different prices for different regions, and the gap can be
twofold. The Uzbekistan price is not the highest in the world, but it is not
the lowest either: neighbouring regions are often cheaper.</p>
<p>Three real examples, read off Steam's own storefront in September 2026:</p>
<table>
<thead>
<tr>
<th>Game</th>
<th>Steam for Uzbekistan</th>
<th>Our price</th>
</tr>
</thead>
<tbody>
<tr>
<td>West Escape</td>
<td>$0.99</td>
<td>$0.78</td>
</tr>
<tr>
<td>Age of Empires IV</td>
<td>$27.99</td>
<td>$21.20</td>
</tr>
<tr>
<td>Black Myth: Wukong</td>
<td>$59.99</td>
<td>$41.45</td>
</tr>
</tbody>
</table>
<p>To be straight about it: this is not always the case. We checked 21 randomly
picked titles from the catalogue — 17 came out cheaper, 2 were roughly level,
and on 2 of them we were dearer. The median saving among the wins was about
15%, the best reached 54%. So the honest wording is &quot;usually cheaper&quot;, not
&quot;always&quot;; the price is shown before you pay, so checking takes ten seconds.</p>
<h2>A Steam gift, not a key</h2>
<p>The mechanism that makes this legal is the Steam gift. The game is bought in a
region where it is available and sent to the recipient's account through
Steam's own gifting system — the same one you use for a friend's birthday.</p>
<p>What follows from that:</p>
<ul>
<li>There is no key to enter anywhere. The game simply appears in the library.</li>
<li>Nobody needs your account password. A public profile link is enough.</li>
<li>The game stays with the recipient for good, like any other purchase.</li>
<li>The account stays yours. No shared account, no rented account.</li>
</ul>
<h2>How to buy, step by step</h2>
<ol>
<li>Find the game in the catalogue by name.</li>
<li>Pick the edition, if there is more than one, and the recipient's account
region.</li>
<li>Paste the Steam profile link. The nickname and avatar appear immediately —
your insurance against a mistyped link.</li>
<li>Pay with an Uzcard or Humo card via Click, Payme or Uzum.</li>
<li>Wait for the gift. It usually arrives within an hour.</li>
</ol>
<h2>The one mistake that matters: account region</h2>
<p>A gift can only be accepted in the region it was bought for. If the
recipient's account belongs to a different country, Steam will simply not let
them click &quot;Accept&quot; — and that is the most common reason an order stalls.</p>
<p>Checking takes half a minute: Steam, then &quot;Account details&quot;, then the
&quot;Country&quot; line. That is the region to pick at checkout. If it does not match,
find out before paying rather than after.</p>
<h2>If the title turns out to be DLC</h2>
<p>DLC only works on top of the base game. You can technically gift an add-on to
someone who does not own the game, but it will do nothing at all until they
buy the base version. Such entries are marked on the card, but it is worth a
glance either way.</p>
<h2>On safety, briefly</h2>
<p>The only thing a gift needs is a profile link. It is public; anyone can see
it.</p>
<p>Nobody should ever ask you for your Steam password, a Steam Guard code, or
access to your email in order to buy you a game. If they do, that is not a
shop, it is account theft, and no price is worth it. The rule is simple and
has no exceptions.</p>$x$,
         $x$How to buy Steam games from Uzbekistan and pay in sum — YuPay$x$, $x$A step-by-step guide: buying Steam games from Uzbekistan, paying in sum with an Uzcard or Humo card, and not getting the account region wrong. With a real price comparison.$x$),
        ('uz', $x$ozbekistondan-steam-oyin-sotib-olish$x$, $x$Oʻzbekistondan Steamda oʻyin qanday sotib olinadi$x$, $x$Oʻzbek kartasi Steamda koʻpincha oʻtmaydi, mintaqamiz uchun narx esa kamdan-kam eng past boʻladi. Oʻyinni qonuniy, soʻmda va odatda arzonroq sotib olish yoʻlini koʻrib chiqamiz.$x$,
         $x$<p>Oʻzbekistondan Steamda oʻyin sotib olishda ikkita alohida toʻsiq bor va ular
odatda bir-biri bilan chalkashtiriladi. Birinchisi: oʻzbek kartasi Steamda
koʻpincha oʻtmaydi. Ikkinchisi, kamroq koʻzga tashlanadigani: toʻlov oʻtgan
taqdirda ham mintaqamiz uchun belgilangan narx kamdan-kam eng past boʻladi.
Quyida ikkalasi bilan nima qilish kerakligi.</p>
<h2>Nega karta oʻtmaydi</h2>
<p>Steam hamma joydan va har qanday karta bilan toʻlovni qabul qilmaydi. Uzcard
va Humo — ichki toʻlov tizimlari, ular chet elda ishlamaydi, xalqaro kartalar
esa hammada ham yoʻq. Internet toʻla boʻlgan aylanma yoʻllar shundan kelib
chiqadi: begona akkauntlar, VPN, «foiz evaziga toʻldirib beraman». Ularning
bir qismi shunchaki noqulay. Bir qismi esa ochiqdan-ochiq xavfli — bu haqda
oxirida.</p>
<h2>Steamdagi narx mintaqaga bogʻliq</h2>
<p>Bu koʻpchilik bilmaydigan asosiy jihat. Steamda oʻyinning yagona narxi yoʻq.
Nashriyotchi turli mintaqalar uchun turli narx belgilaydi va farq ikki
barobargacha boʻlishi mumkin. Oʻzbekiston uchun narx dunyodagi eng yuqori
emas, lekin eng past ham emas: qoʻshni mintaqalar koʻpincha arzonroq.</p>
<p>2026-yil sentabrida Steamning oʻz vitrinasidan olingan uchta haqiqiy misol:</p>
<table>
<thead>
<tr>
<th>Oʻyin</th>
<th>Steam, Oʻzbekiston uchun</th>
<th>Bizning narx</th>
</tr>
</thead>
<tbody>
<tr>
<td>West Escape</td>
<td>$0.99</td>
<td>$0.78</td>
</tr>
<tr>
<td>Age of Empires IV</td>
<td>$27.99</td>
<td>$21.20</td>
</tr>
<tr>
<td>Black Myth: Wukong</td>
<td>$59.99</td>
<td>$41.45</td>
</tr>
</tbody>
</table>
<p>Darrov va rostini aytamiz: bu har doim ham shunday emas. Katalogdan 21 ta
tasodifiy oʻyinni tekshirdik — 17 tasi arzonroq chiqdi, 2 tasi taxminan teng,
2 tasida esa biz qimmatroq edik. Yutuqli holatlarda oʻrtacha tejash 15%
atrofida, eng kattasi 54% gacha yetdi. Shuning uchun toʻgʻri ibora — «odatda
arzonroq», «har doim» emas; narx toʻlovdan oldin koʻrinadi, oʻzingiz oʻn
soniyada solishtirasiz.</p>
<h2>Steam sovgʻasi, kalit emas</h2>
<p>Buni qonuniy qiladigan mexanizm Steam sovgʻasi deb ataladi. Oʻyin u mavjud
boʻlgan mintaqada sotib olinadi va Steamning oʻz sovgʻa tizimi orqali qabul
qiluvchining akkauntiga yuboriladi — xuddi doʻstingizga tugʻilgan kunga
sovgʻa qilganingizdek.</p>
<p>Bundan kelib chiqadigan xulosalar:</p>
<ul>
<li>Hech qayerga kalit kiritish shart emas. Oʻyin kutubxonada oʻzi paydo boʻladi.</li>
<li>Akkaunt paroli hech kimga kerak emas. Profilga ochiq havola yetarli.</li>
<li>Oʻyin qabul qiluvchida butunlay qoladi, xuddi sotib olingan boshqasi kabi.</li>
<li>Akkaunt sizniki boʻlib qolaveradi. Hech qanday «umumiy» yoki «ijaraga
olingan» akkaunt yoʻq.</li>
</ul>
<h2>Qanday sotib olinadi: bosqichma-bosqich</h2>
<ol>
<li>Katalogdan oʻyinni nomi boʻyicha toping.</li>
<li>Agar bir nechta boʻlsa, nashrni va qabul qiluvchi akkaunti mintaqasini
tanlang.</li>
<li>Steam profiliga havolani joylashtiring. Taxallus va avatar darhol
koʻrinadi — bu havoladagi xatodan sugʻurta.</li>
<li>Uzcard yoki Humo kartasi bilan Click, Payme yoki Uzum orqali toʻlang.</li>
<li>Sovgʻani kuting. U odatda bir soat ichida keladi.</li>
</ol>
<h2>Asosiy xato — akkaunt mintaqasi</h2>
<p>Sovgʻani faqat u sotib olingan mintaqada qabul qilish mumkin. Agar qabul
qiluvchining akkaunti boshqa mamlakatga tegishli boʻlsa, Steam «Qabul qilish»
tugmasini bosishga ruxsat bermaydi — buyurtma toʻxtab qolishining eng keng
tarqalgan sababi shu.</p>
<p>Yarim daqiqada tekshiriladi: Steam → «Akkaunt haqida» → «Mamlakat» qatori.
Buyurtma rasmiylashtirishda aynan shu mintaqani tanlash kerak. Agar mos
kelmasa, buni toʻlovdan keyin emas, oldin aniqlagan maʼqul.</p>
<h2>Agar oʻyin qoʻshimcha boʻlib chiqsa</h2>
<p>DLC faqat asosiy oʻyin ustiga ishlaydi. Asosiy oʻyini yoʻq odamga qoʻshimchani
sovgʻa qilish texnik jihatdan mumkin, lekin u asosiy versiyani sotib olmaguncha
bundan hech qanday foyda boʻlmaydi. Bunday pozitsiyalar kartochkada
belgilangan, ammo baribir bir koʻz tashlagan yaxshi.</p>
<h2>Xavfsizlik haqida, qisqacha</h2>
<p>Sovgʻa uchun kerak boʻlgan yagona narsa — profilga havola. U ochiq, uni
istalgan odam koʻradi.</p>
<p>Hech kim va hech qachon sizdan oʻyin sotib olish uchun Steam parolini, Steam
Guard kodini yoki pochtangizga kirishni soʻramasligi kerak. Agar soʻrashsa —
bu doʻkon emas, akkaunt oʻgʻirligi, va hech qanday narx bunga arzimaydi. Qoida
oddiy va istisnosi yoʻq.</p>$x$,
         $x$Oʻzbekistondan Steamda oʻyinni soʻmda sotib olish — YuPay$x$, $x$Bosqichma-bosqich qoʻllanma: Oʻzbekistondan Steam oʻyinini sotib olish, Uzcard yoki Humo bilan soʻmda toʻlash va akkaunt mintaqasida xato qilmaslik. Haqiqiy narx solishtiruvi bilan.$x$)
    ) AS v(locale, slug, title, excerpt, body_html, seo_title, seo_description)
)
INSERT INTO blog_post_faqs (id, post_id, locale, sort_order, question, answer)
SELECT gen_random_uuid(), np.id, v.locale, v.sort_order, v.question, v.answer
FROM new_post np, (VALUES
    (1, 'ru', $x$Можно ли оплатить Steam узбекистанской картой?$x$,
     $x$Напрямую в Steam — чаще всего нет: Uzcard и Humo за пределами страны не работают. У нас оплата идёт в сумах этими же картами через Click, Payme или Uzum, а игра приходит на аккаунт подарком Steam.$x$),
    (1, 'en', $x$Can I pay Steam with an Uzbek card?$x$,
     $x$Directly on Steam, usually not: Uzcard and Humo do not work outside the country. Here you pay in sum with those same cards via Click, Payme or Uzum, and the game reaches the account as a Steam gift.$x$),
    (1, 'uz', $x$Steamga oʻzbek kartasi bilan toʻlash mumkinmi?$x$,
     $x$Toʻgʻridan-toʻgʻri Steamda — koʻpincha yoʻq: Uzcard va Humo mamlakatdan tashqarida ishlamaydi. Bizda toʻlov aynan shu kartalar bilan Click, Payme yoki Uzum orqali soʻmda amalga oshadi, oʻyin esa akkauntga Steam sovgʻasi sifatida keladi.$x$),
    (2, 'ru', $x$Подарок Steam — это законно?$x$,
     $x$Да. Подарок — штатная функция самого Steam: так игру дарят другу на день рождения. Аккаунт остаётся ваш, никакие правила Steam при этом не нарушаются, а игра остаётся в библиотеке навсегда.$x$),
    (2, 'en', $x$Is a Steam gift legitimate?$x$,
     $x$Yes. Gifting is a built-in Steam feature — it is how you give a friend a game for their birthday. The account stays yours, no Steam rule is broken, and the game stays in the library for good.$x$),
    (2, 'uz', $x$Steam sovgʻasi qonuniymi?$x$,
     $x$Ha. Sovgʻa — Steamning oʻz funksiyasi: doʻstga tugʻilgan kunga oʻyin shunday sovgʻa qilinadi. Akkaunt sizniki boʻlib qoladi, Steam qoidalari buzilmaydi, oʻyin esa kutubxonada butunlay qoladi.$x$),
    (3, 'ru', $x$Что будет, если игра уже есть у получателя?$x$,
     $x$Steam не даст принять такой подарок — он останется в списке ожидающих. Поэтому перед покупкой стоит уточнить у получателя, нет ли игры в библиотеке: это единственная проверка, которую мы сделать за вас не можем.$x$),
    (3, 'en', $x$What if the recipient already owns the game?$x$,
     $x$Steam will not let them accept such a gift — it stays in their pending list. So it is worth asking the recipient whether the game is already in their library: that is the one check we cannot make for you.$x$),
    (3, 'uz', $x$Agar oʻyin qabul qiluvchida allaqachon boʻlsa nima boʻladi?$x$,
     $x$Steam bunday sovgʻani qabul qildirmaydi — u kutilayotganlar roʻyxatida qoladi. Shuning uchun sotib olishdan oldin qabul qiluvchidan oʻyin kutubxonasida yoʻqligini soʻrash kerak: bu biz siz uchun qila olmaydigan yagona tekshiruv.$x$),
    (4, 'ru', $x$Можно ли купить игру себе, а не в подарок?$x$,
     $x$Да, и это самый частый случай. Просто укажите ссылку на свой собственный профиль Steam — подарок придёт вам, и игра встанет в вашу библиотеку.$x$),
    (4, 'en', $x$Can I buy a game for myself rather than as a gift?$x$,
     $x$Yes, and that is the common case. Just give the link to your own Steam profile — the gift comes to you and the game lands in your library.$x$),
    (4, 'uz', $x$Oʻyinni sovgʻa sifatida emas, oʻzimga sotib olsam boʻladimi?$x$,
     $x$Ha, va bu eng koʻp uchraydigan holat. Shunchaki oʻz Steam profilingizga havolani koʻrsating — sovgʻa sizga keladi va oʻyin kutubxonangizga tushadi.$x$)
) AS v(sort_order, locale, question, answer);

COMMIT;
