/**
 * The B2B (merchant) slice of the catalog feature: DTOs, fetch helpers and
 * the price-preview math for the Task-8 admin controls.
 *
 * DTOs mirror the generated `@yupay/api-client` types (`SkuB2bOut`,
 * `BrandB2bOut`, `BulkMarkupIn` / `BulkMarkupOut` in
 * `packages/api-client/src/generated/types.gen.ts`, regenerated by
 * `make gen-api`) — mirrored rather than imported because the generated
 * output is gitignored and the committed `packages/api-client/src/types.ts`
 * is a placeholder stub, so a direct import would not typecheck on a fresh
 * checkout (CI's lint-ts job never runs `gen:api`). This is the admin SPA's
 * established thin hand-written DTO convention
 * (`features/payments/providers/types.ts` explains it). Deliberately NOT
 * reusing `features/wallet/types.ts` — its unions are stale (see
 * `features/merchants/api.ts`).
 *
 * Strings live in `@yupay/i18n/locales/{ru,en,uz}/admin.json` (parity
 * CI-gated); the admin SPA is Russian-only today, so the feature reads the
 * `ru` catalog directly, same as `features/merchants`.
 */

import adminRu from "@yupay/i18n/locales/ru/admin.json";

import { apiPatch, apiPost } from "@/lib/api";

/** The feature's Russian string catalog (see module docstring). */
export const T = adminRu.catalogB2b;

/** The B2B slice of a SKU after a patch (mirrors `SkuB2bOut`). */
export interface SkuB2bOut {
  id: string;
  sku_code: string;
  visible_b2b: boolean;
  b2b_markup_pct: string;
}

/** The B2B slice of a brand after a patch (mirrors `BrandB2bOut`). */
export interface BrandB2bOut {
  id: string;
  slug: string;
  visible_b2b: boolean;
}

/** How many SKUs a bulk markup touched (mirrors `BulkMarkupOut`). */
export interface BulkMarkupOut {
  affected: number;
}

export function patchSkuB2b(
  skuId: string,
  body: { markup_pct: string; visible_b2b: boolean },
  idempotencyKey: string,
): Promise<SkuB2bOut> {
  return apiPatch<SkuB2bOut>(`/api/v1/admin/catalog/skus/${skuId}/b2b`, body, {
    "Idempotency-Key": idempotencyKey,
  });
}

export function patchBrandB2b(
  brandId: string,
  visibleB2b: boolean,
  idempotencyKey: string,
): Promise<BrandB2bOut> {
  return apiPatch<BrandB2bOut>(
    `/api/v1/admin/catalog/brands/${brandId}/b2b`,
    { visible_b2b: visibleB2b },
    { "Idempotency-Key": idempotencyKey },
  );
}

export function postBulkMarkup(
  brandSlug: string,
  markupPct: string,
  idempotencyKey: string,
): Promise<BulkMarkupOut> {
  return apiPost<BulkMarkupOut>(
    "/api/v1/admin/catalog/b2b/bulk-markup",
    { brand_slug: brandSlug, markup_pct: markupPct },
    { "Idempotency-Key": idempotencyKey },
  );
}

/**
 * Canonical `Numeric(5,2)`-shaped markup (`"7"` / `"-2.5"`) from operator
 * input, or `null` when the column cannot hold it. Accepts comma decimals
 * like the money inputs do. Negative values are legal by explicit ruling —
 * the order-time margin floor is the money guard, not this parser.
 */
export function parseMarkupPct(raw: string): string | null {
  const cleaned = raw.replace(/\s/g, "").replace(",", ".");
  if (!/^-?\d{1,3}(\.\d{1,2})?$/.test(cleaned)) return null;
  return cleaned;
}

export interface B2bPreview {
  /** Canonical two-decimal price string, e.g. `"8.56"` or `"-0.03"`. */
  price: string;
  /** True when the previewed price is below cost (only a negative markup
   *  can cause it — the ceiling otherwise keeps price ≥ cost). */
  belowCost: boolean;
}

/**
 * B2B price preview: `ceil_to_cent(cost × (1 + markup / 100))`.
 *
 * THE one sanctioned client-side copy of the merchant pricing formula.
 * `apps/api/src/yupay/modules/merchants/pricing.py::merchant_price` is the
 * authority; this exists ONLY so the admin form can show the effect before
 * saving (always labelled «предварительно» in the UI) and must be kept in
 * exact lock-step with it. The 0.01-ceiling is integer (BigInt) math on the
 * decimal strings — `Math.ceil(x * 100) / 100` over floats disagrees with
 * the server's Decimal `ROUND_CEILING` (0.07 × 100 → 7.000000000000001 →
 * 0.08), and a preview that rounds differently from the server is worse
 * than none.
 *
 * Derivation, with cost = C·10⁻ᶜ and markup = K·10⁻ᵐ (C, K integers):
 *
 *     price = cost × (100 + markup) / 100
 *     cents = ⌈price × 100⌉ = ⌈C × (100·10ᵐ + K) / 10ᶜ⁺ᵐ⌉
 *
 * Returns `null` while either input is missing or half-typed, so a stale
 * preview never freezes on screen.
 */
export function previewB2bPrice(costRaw: string, markupRaw: string): B2bPreview | null {
  const cost = parseDecimal(costRaw, { signed: false });
  const markup = parseDecimal(markupRaw, { signed: true });
  if (!cost || !markup) return null;
  const num = cost.units * (100n * pow10(markup.scale) + markup.units);
  const cents = ceilDiv(num, pow10(cost.scale + markup.scale));
  // price < cost ⇔ cents / 100 < C / 10ᶜ ⇔ cents × 10ᶜ < C × 100
  const belowCost = cents * pow10(cost.scale) < cost.units * 100n;
  return { price: formatCents(cents), belowCost };
}

interface ParsedDecimal {
  units: bigint;
  scale: number;
}

function parseDecimal(raw: string, opts: { signed: boolean }): ParsedDecimal | null {
  const cleaned = raw.replace(/\s/g, "").replace(",", ".");
  const match = /^(-?)(\d+)(?:\.(\d+))?$/.exec(cleaned);
  if (!match) return null;
  const [, sign = "", int = "", frac = ""] = match;
  if (sign && !opts.signed) return null;
  const units = BigInt(int + frac);
  return { units: sign ? -units : units, scale: frac.length };
}

function pow10(n: number): bigint {
  return 10n ** BigInt(n);
}

/** Ceiling division for a positive divisor — toward +∞, like ROUND_CEILING. */
function ceilDiv(n: bigint, d: bigint): bigint {
  return n >= 0n ? (n + d - 1n) / d : -(-n / d);
}

function formatCents(cents: bigint): string {
  const negative = cents < 0n;
  const abs = negative ? -cents : cents;
  const int = abs / 100n;
  const frac = (abs % 100n).toString().padStart(2, "0");
  return `${negative ? "-" : ""}${int.toString()}.${frac}`;
}
