"""Public surface of the ``fulfillment`` module."""

from yupay.modules.fulfillment.models import (
    Delivery,
    FulfillmentAttempt,
    FulfillmentTask,
)
from yupay.modules.fulfillment.routes import admin_router, router
from yupay.modules.fulfillment.schemas import (
    AttemptAdminListOut,
    AttemptAdminOut,
    DeliveryListOut,
    DeliveryOut,
    FulfillmentAttemptOut,
    FulfillmentTaskListOut,
    FulfillmentTaskOut,
    ManualCompleteIn,
    ManualFailIn,
)
from yupay.modules.fulfillment.service import (
    BUYER_SAFE_ARTIFACT_KEYS,
    MONEY_OUTCOME_KEY,
    buyer_safe_artifact,
    cancel_open_tasks_for_order,
    cancel_task,
    complete_manual_task,
    drain_pending_tasks,
    fail_manual_task,
    get_task_admin,
    list_attempts_admin,
    list_deliveries_for_order,
    list_tasks_admin,
    money_outcome_of,
    process_task,
    process_webhook_update,
    retry_task,
    start_for_order,
)
from yupay.modules.fulfillment.suppliers import (
    Fulfiller,
    FulfillerError,
    FulfillerNotIntegratedError,
    FulfillResult,
    FulfillStatus,
    MoneyOutcome,
    available_suppliers,
    get_fulfiller,
)

__all__ = [
    "BUYER_SAFE_ARTIFACT_KEYS",
    "MONEY_OUTCOME_KEY",
    "AttemptAdminListOut",
    "AttemptAdminOut",
    "Delivery",
    "DeliveryListOut",
    "DeliveryOut",
    "FulfillResult",
    "FulfillStatus",
    "Fulfiller",
    "FulfillerError",
    "FulfillerNotIntegratedError",
    "FulfillmentAttempt",
    "FulfillmentAttemptOut",
    "FulfillmentTask",
    "FulfillmentTaskListOut",
    "FulfillmentTaskOut",
    "ManualCompleteIn",
    "ManualFailIn",
    "MoneyOutcome",
    "admin_router",
    "available_suppliers",
    "buyer_safe_artifact",
    "cancel_open_tasks_for_order",
    "cancel_task",
    "complete_manual_task",
    "drain_pending_tasks",
    "fail_manual_task",
    "get_fulfiller",
    "get_task_admin",
    "list_attempts_admin",
    "list_deliveries_for_order",
    "list_tasks_admin",
    "money_outcome_of",
    "process_task",
    "process_webhook_update",
    "retry_task",
    "router",
    "start_for_order",
]
